### PR TITLE
Added two new trigger candidate types for ICEBERG

### PR DESCRIPTION
**Pull request by bieryAtFnal**
I have tried to follow the style of existing TC type names.

I would appreciate it if experts could provide feedback.

### CODE REVIEW

**Comment by MRiganSUSX** [comment]
Hi Kurt,
I have no issues with the naming. I do have a comment and a question though:

Question: Do we want to increase the `s_trigger_candidate_version` just because we added TC types? In my understanding, this was meant to reflect when we changed the actual parameters of the TC object (added, removed, changed data type and therefore size).

Comment: 
Unless there is a reason not to, please add the new types to pybind enums as well:
https://github.com/DUNE-DAQ/trgdataformats/blob/production/v4/pybindsrc/trigger_candidate.cpp#L68-L110

**Comment by bieryAtFnal** [comment]
Thanks @MRiganSUSX , both of those are good points.

I've added the Python entries and backed out the version change.

**Review by MRiganSUSX — APPROVED** [review]
LGTM.

As mentioned, there will be some new types added for CRT group as well. We may need to coordinate merging.

**Comment by bieryAtFnal** [comment]
Closing this PR since its changes have been included in #30

**Pull request closed without merging**
