### PR TITLE
MLT: Coincidence trigger (trigger deliverable for v4.1.0)

### PR DESCRIPTION
**Pull request by MRiganSUSX**
This is the implementation of coincidence trigger as discussed in
[Trigger: issue 220](https://github.com/DUNE-DAQ/trigger/issues/220)

### CODE REVIEW

**Comment by strilov** [comment]
Hi Michal. Shouldn't the return type of string_to_fragment_type_value be TriggerCandidateData::Type rather than an int?

**Comment by MRiganSUSX** [comment]
Hi Stoyan. It could, however, I prefer working with integers and the functions down the flow expect integers and produce bitsets of integers. So TLDR, I could change it to type here, but would convert to integer at some later point anyway, so I prefer it like this.

**Comment by strilov** [comment]
Hi Michal. I still think returning the actual type from that function would be beneficial. I would imagine that most users of that function would expect it to return the type. For better or for worse, if using scoped enums, explicit conversions are not easily unavoidable.

Also, should an exception or an ers:error/ers::warning be raised when an unrecognised string is passed in? or should kUnknown be returned? Similar to this: https://github.com/DUNE-DAQ/daqdataformats/blob/develop/include/daqdataformats/FragmentHeader.hpp#L268

**Comment by MRiganSUSX** [comment]
Hi Stoyan, thanks for your comment. 
I purposely named the function `string_to_fragment_type_value` to highlight that it is not just returning the type. I'm happy to make another function that would just be `string_to_fragment_type` however it would (currently) be unused.
Regarding the exception/error, this is taken care of by daqconf here: [daqconf:trigger_gen](https://github.com/DUNE-DAQ/daqconf/blob/fc87e01a177eba1c515c88fab9360d1bc34d59f9/python/daqconf/apps/trigger_gen.py#L86).

**Pull request merged**
